services:
  simintbot-admin-app-dev:
    container_name: simintbot-admin-app-dev
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - API_URL=https://devapi.simint-bot.com/api/v1
    ports:
      - "3004:3000"
    restart: always
    env_file:
      - .env
      - .env.local
