services:
  simintbot-admin-app-prod:
    container_name: simintbot-admin-app-prod
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - API_URL=https://api.simint-bot.com/api/v1
    ports:
      - "3003:3000"
    restart: always
    env_file:
      - .env
      - .env.local
